<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Description>Adapter biblioteki Mass.AddressWindow.Pdf do portu domenowego.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mass.AddressWindow.Domain\Mass.AddressWindow.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\src\Mass.AddressWindow.Pdf\Mass.AddressWindow.Pdf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>

</Project>
